hotel_info_data = {
    "debug": None,
    "error": None,
    "status": "ok",
    "data": {
        "address": "Россия, Белогорск",
        "amenity_groups": [
            {
                "amenities": ["Памятка по безопасности"],
                "group_name": "Санитарные меры",
            },
            {
                "amenities": [
                    "Компьютер",
                    "Кондиционер",
                    "Отопление",
                    "Охрана",
                    "Стиральная машина",
                    "Сад",
                    "Терраса",
                    "Сушилка",
                    "Огнетушитель",
                    "Курение разрешено",
                    "Посудомоечная машина",
                    "Патио",
                ],
                "group_name": "Общее",
            },
            {
                "amenities": [
                    "Пресс для брюк",
                    "Кабельное телевидение",
                    "Телевизор",
                    "Мини-бар",
                    "DVD-плеер",
                    "Запирающийся шкафчик",
                    "Халат",
                    "Москитная сетка",
                    "Сейф (в номере)",
                ],
                "group_name": "В номерах",
            },
            {
                "amenities": [
                    "Удобства для гостей с ограниченными физическими возможностями",
                    "Работают лифты для доступа к верхним этажам",
                ],
                "group_name": "Доступность",
            },
            {
                "amenities": [
                    "Гладильные принадлежности",
                    "Фен (по запросу)",
                    "Телефон",
                    "Утюг",
                ],
                "group_name": "Услуги и удобства",
            },
            {
                "amenities": [
                    "Общая кухня",
                    "Холодильник",
                    "Кухня",
                    "Микроволновая печь",
                ],
                "group_name": "Питание",
            },
            {
                "amenities": [
                    "Бесплатный Wi-Fi",
                    "Бесплатный доступ в интернет",
                ],
                "group_name": "Интернет",
            },
            {
                "amenities": [
                    "на испанском",
                    "на немецком",
                    "на русском",
                    "на английском",
                    "на итальянском",
                ],
                "group_name": "Персонал говорит",
            },
            {"amenities": ["Терраса для загара"], "group_name": "Развлечения"},
            {"amenities": ["Ксерокс"], "group_name": "Бизнес"},
            {
                "amenities": ["Аптечка первой помощи"],
                "group_name": "Красота и здоровье",
            },
            {
                "amenities": ["Помещение для хранения лыж"],
                "group_name": "Зимние виды спорта",
            },
        ],
        "check_in_time": "14:00:00",
        "check_out_time": "12:00:00",
        "description_struct": [
            {
                "paragraphs": [
                    "Расположение",
                    "Внимание! Данная страница является тестовой.",
                    "Размещенный на странице отель является вымышленным и не подлежит бронированию. В случае бронирования данного отеля размещение не может быть предоставлено.",
                    "В отеле",
                    "Внимание!",
                    "Размещенный на странице отель является вымышленным и не подлежит бронированию. В случае бронирования данного отеля размещение не может быть предоставлено.",
                ],
                "title": None,
            }
        ],
        "email": "test@horse.world",
        "id": "test_hotel",
        "images": [
            "https://cdn.ostrovok.ru/t/{size}/ext/d0/2d/d02d4e256be403655c28382497e90c20e9c61234.jpeg",
            "https://cdn.ostrovok.ru/t/{size}/ext/17/1c/171c7435fafa712c4042ebd0a6bb044198e36844.jpeg",
            "https://cdn.ostrovok.ru/t/{size}/ext/11/f5/11f5e1a460fa2e97c03888e8bb677b0d440d5e7a.jpeg",
            "https://cdn.ostrovok.ru/t/{size}/ext/7f/12/7f128f356327a1e2b38ef71e09894a072c861032.jpeg",
            "https://cdn.ostrovok.ru/t/{size}/ext/ec/4d/ec4dfc4383a045fc616a78416e14e1b8fac04a5b.jpeg",
        ],
        "kind": "Hostel",
        "latitude": 50.921288,
        "longitude": 128.47388,
        "name": "Тест отель (НЕ ЯВЛЯЕТСЯ ОТЕЛЕМ - НЕ ДЛЯ БРОНИРОВАНИЯ)",
        "metapolicy_struct": {
            "internet": [
                {
                    "currency": "AUD",
                    "inclusion": "not_included",
                    "internet_type": "wireless",
                    "price": 100.0,
                    "price_unit": "per_week",
                    "work_area": "room",
                },
                {
                    "currency": "BDT",
                    "inclusion": "not_included",
                    "internet_type": "wired",
                    "price": 200.0,
                    "price_unit": "per_hour",
                    "work_area": "hotel",
                },
            ],
            "add_fee": [
                {
                    "currency": "AFN",
                    "fee_type": "towels",
                    "price": 100.0,
                    "price_unit": "per_week",
                },
                {
                    "currency": "AFN",
                    "fee_type": "refrigerator",
                    "price": 200.0,
                    "price_unit": "per_room_per_night",
                },
                {
                    "currency": "BGN",
                    "fee_type": "safe",
                    "price": 50.0,
                    "price_unit": "per_guest_per_night",
                },
            ],
            "check_in_check_out": None,
            "children": [
                {
                    "age_end": 0,
                    "age_start": 2,
                    "currency": "AMD",
                    "extra_bed": "available",
                    "price": 100.0,
                },
                {
                    "age_end": 3,
                    "age_start": 1,
                    "currency": "ARS",
                    "extra_bed": "available",
                    "price": 200.0,
                },
            ],
            "children_meal": [
                {
                    "age_end": 15,
                    "age_start": 10,
                    "currency": "ANG",
                    "inclusion": "not_included",
                    "meal_type": "lunch",
                    "price": 100.0,
                }
            ],
            "cradle": None,
            "deposit": [
                {
                    "availability": "available",
                    "currency": None,
                    "deposit_type": "unspecified",
                    "payment_type": "unspecified",
                    "price": 10.0,
                    "price_unit": "per_guest_per_night",
                    "pricing_method": "percent",
                }
            ],
            "extra_bed": [
                {
                    "amount": 0,
                    "currency": None,
                    "inclusion": "not_included",
                    "price": 0.0,
                    "price_unit": "unspecified",
                }
            ],
            "meal": [
                {
                    "currency": "AED",
                    "inclusion": "not_included",
                    "meal_type": "breakfast",
                    "price": 100.0,
                },
                {
                    "currency": "AOA",
                    "inclusion": "not_included",
                    "meal_type": "full-board",
                    "price": 500.0,
                },
                {
                    "currency": "ARS",
                    "inclusion": "not_included",
                    "meal_type": "ultra-all-inclusive",
                    "price": 400.0,
                },
            ],
            "no_show": {
                "availability": "available",
                "day_period": "after_midday",
                "time": "12:00:00",
            },
            "parking": [
                {
                    "currency": "RUB",
                    "inclusion": "not_included",
                    "territory_type": "on_side",
                    "price": 200.0,
                    "price_unit": "per_guest_per_night",
                }
            ],
            "pets": [
                {
                    "currency": None,
                    "inclusion": "included",
                    "pets_type": "unspecified",
                    "price": 0.0,
                    "price_unit": "unspecified",
                }
            ],
            "shuttle": [
                {
                    "currency": "ALL",
                    "inclusion": "not_included",
                    "shuttle_type": "one_way",
                    "price": 300.0,
                    "destination_type": "ship",
                },
                {
                    "currency": None,
                    "inclusion": "not_included",
                    "shuttle_type": "unspecified",
                    "price": 0.0,
                    "destination_type": "unspecified",
                },
                {
                    "currency": None,
                    "inclusion": "not_included",
                    "shuttle_type": "unspecified",
                    "price": 0.0,
                    "destination_type": "unspecified",
                },
            ],
            "visa": {"visa_support": "support_enable"},
        },
        "phone": "+7 0000000012",
        "policy_struct": [
            {
                "paragraphs": [
                    "Цена дополнительного завтрака: 100.00 AED на человека. Информация о типе питания, включенном в стоимость, указана в деталях тарифа."
                ],
                "title": "Питание",
            },
            {
                "paragraphs": [
                    "Дополнительные кровати предоставляются за дополнительную плату.",
                    "Количество дополнительных кроватей зависит от категории номера. Необходимо ознакомиться с информацией о вместимости выбранного номера.",
                    "Стоимость обеда для детей в возрасте от 10 до 15 лет: 100.00 ANG.",
                    "В зависимости от вместимости выбранного номера плата за проживание детей в возрасте от 2 лет при условии их размещения в одной комнате с родителями или опекунами на дополнительных кроватях (детских кроватках/люльках) составляет 100.00 AMD за ночь.",
                ],
                "title": "Размещение с детьми и информация о дополнительных кроватях",
            },
            {
                "paragraphs": [
                    "Early check-in and/or late check-out is available for an additional fee. Cost: 120.00 AFN.",
                    "Если для въезда в страну вам требуется виза, ваш отель в большинстве случаев предоставит вам необходимые документы для ее получения. За более подробной информацией обращайтесь в отель, контактная информация указана в подтверждении бронирования. За эти услуги может взиматься дополнительная плата, даже в случае последующей отмены бронирования. Все договоренности осуществляются исключительно между вами и отелем.",
                    "Внимание! Если вы не заселитесь в номер до 12:00 PM ночи, бронирование будет отменено.",
                ],
                "title": "Особые условия проживания",
            },
            {
                "paragraphs": [
                    "Chargeable parking available on the premises. Cost: 200.00 RUB per day."
                ],
                "title": "Парковка",
            },
            {
                "paragraphs": [
                    "Предоставляется трансфер от/до морского порта. Стоимость: 300.00 ALL в одну сторону."
                ],
                "title": "Трансфер",
            },
            {
                "paragraphs": ["VERY IMPORTANT INFORMATION"],
                "title": "Дополнительно",
            },
        ],
        "postal_code": None,
        "region": {
            "country_code": "RU",
            "iata": None,
            "id": 6308866,
            "name": "Белогорск",
            "type": "City",
        },
        "room_groups": [
            {
                "images": [],
                "name": "Кровать в общем номере с двухъярусной кроватью",
                "room_amenities": [],
                "room_group_id": 6,
                "rg_ext": {
                    "rg_class": 1,
                    "quality": 0,
                    "sex": 0,
                    "bathroom": 1,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/extranet/a8/94/a89451275d8b88bc8957c83b39d3c379a0183119.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/03/46/0346a5728dac78d47b54a627b5a83c6f78e400a8.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/ef/55/ef558b09ce7022202e47d72ce3b249eee5b36776.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/7d/05/7d0552b5198d247bd2fb73ce48514837976d6120.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/cd/dc/cddca82b47d1a70e72fd365b27ceaacdff4d5fc7.jpeg",
                ],
                "name": "Номер Economy с различными типами кроватей",
                "room_amenities": ["iron", "washing-machine"],
                "room_group_id": 10,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 1,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/ext/06/90/0690f13918e6808c03212b40619f466123c5d966.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/07/b0/07b0a97fc5601a80440c3cd58fedd7ffe684d600.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/65/ef/65efcc19b968db5cbc44f7ac6dbf02cb9e757831.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/07/a6/07a68a8a271c174a252998063ffdeb5b88475fb2.jpeg",
                ],
                "name": "Номер Standard с различными типами кроватей",
                "room_amenities": ["kitchen", "shared-bathroom", "tea"],
                "room_group_id": 11,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 2,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Коттедж с различными типами кроватей",
                "room_amenities": [],
                "room_group_id": 17,
                "rg_ext": {
                    "rg_class": 9,
                    "quality": 0,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/ext/00/47/0047179b096a61f4768ed9c3f0430a26c8080962.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/93/c1/93c1880a6b3cace46a21f3cf7b02277f36aee3f3.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/c5/ef/c5ef35b36b5a165f06e209877d507541df86c8fb.jpeg",
                ],
                "name": "Номер Economy с двуспальной кроватью",
                "room_amenities": ["iron", "washing-machine"],
                "room_group_id": 71,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 1,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/extranet/cd/dc/cddca82b47d1a70e72fd365b27ceaacdff4d5fc7.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/a8/94/a89451275d8b88bc8957c83b39d3c379a0183119.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/03/46/0346a5728dac78d47b54a627b5a83c6f78e400a8.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/ef/55/ef558b09ce7022202e47d72ce3b249eee5b36776.png",
                    "https://cdn.ostrovok.ru/t/{size}/extranet/7d/05/7d0552b5198d247bd2fb73ce48514837976d6120.png",
                ],
                "name": "Номер Economy с 2 отдельными кроватями",
                "room_amenities": ["iron", "washing-machine"],
                "room_group_id": 72,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 1,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 4,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/ext/b7/ea/b7ea6f8762b300e955786f00782f523436f055ba.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/ca/eb/caeb031a19e94943dfebe938385872289553171a.jpeg",
                ],
                "name": "Номер Economy с двухъярусной кроватью",
                "room_amenities": ["iron", "washing-machine"],
                "room_group_id": 73,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 1,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 1,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Номер Standard с двуспальной кроватью",
                "room_amenities": ["kitchen", "shared-bathroom", "tea"],
                "room_group_id": 90,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 2,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/ext/a0/2c/a02ca9548ec01184cadbee9e4b7ccf7e6a3a2229.jpeg"
                ],
                "name": "Номер Standard с 2 отдельными кроватями",
                "room_amenities": ["pillows", "telephone"],
                "room_group_id": 91,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 2,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 4,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Номер Standard с различными типами кроватей",
                "room_amenities": [],
                "room_group_id": 94,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 2,
                    "sex": 0,
                    "bathroom": 1,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Семейный номер Standard с различными типами кроватей",
                "room_amenities": [],
                "room_group_id": 99,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 18,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 0,
                    "family": 1,
                    "capacity": 0,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Номер Comfort с 2 отдельными кроватями",
                "room_amenities": [],
                "room_group_id": 110,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 3,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 4,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Номер Superior с двуспальной кроватью",
                "room_amenities": [],
                "room_group_id": 123,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 5,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Номер Deluxe с двуспальной кроватью",
                "room_amenities": [],
                "room_group_id": 130,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 6,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Люкс Junior с двуспальной кроватью",
                "room_amenities": ["toiletries"],
                "room_group_id": 166,
                "rg_ext": {
                    "rg_class": 4,
                    "quality": 0,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [
                    "https://cdn.ostrovok.ru/t/{size}/ext/01/86/0186f5943db2d26859068ca9d3d76c6a148fa8d8.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/aa/50/aa50cf3841096e74f14dad4b87e32718ccbd56b0.jpeg",
                    "https://cdn.ostrovok.ru/t/{size}/ext/52/3a/523adc6181decc8d89043e66529119ecd75f5911.jpeg",
                ],
                "name": "Люкс с двуспальной кроватью",
                "room_amenities": [
                    "mirror",
                    "private-bathroom",
                    "safe",
                    "sauna",
                    "telephone",
                    "toiletries",
                    "towels",
                    "tv",
                    "window",
                ],
                "room_group_id": 173,
                "rg_ext": {
                    "rg_class": 5,
                    "quality": 0,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Апартаменты с двуспальной кроватью",
                "room_amenities": [],
                "room_group_id": 226,
                "rg_ext": {
                    "rg_class": 6,
                    "quality": 4,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Апартаменты Superior с двуспальной кроватью",
                "room_amenities": [],
                "room_group_id": 233,
                "rg_ext": {
                    "rg_class": 6,
                    "quality": 5,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Студия с двуспальной кроватью",
                "room_amenities": [],
                "room_group_id": 250,
                "rg_ext": {
                    "rg_class": 7,
                    "quality": 0,
                    "sex": 0,
                    "bathroom": 2,
                    "bedding": 3,
                    "family": 0,
                    "capacity": 2,
                    "club": 0,
                },
            },
            {
                "images": [],
                "name": "Трёхместный номер Economy",
                "room_amenities": [],
                "room_group_id": 21537316,
                "rg_ext": {
                    "rg_class": 3,
                    "quality": 1,
                    "sex": 0,
                    "bathroom": 1,
                    "bedding": 0,
                    "family": 0,
                    "capacity": 3,
                    "club": 0,
                },
            },
        ],
        "star_rating": 0,
        "serp_filters": [
            "has_internet",
            "air_conditioning",
            "has_disabled_support",
            "has_smoking",
        ],
        "is_closed": False,
    },
}
hotel_info_error_response = {
    "debug": None,
    "error": "hotel_not_found",
    "status": "error",
    "data": None,
}
