overview_response = {
    "debug": None,
    "error": None,
    "status": "ok",
    "data": [
        {
            "endpoint": "api/b2b/v3/general/contract/data/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/general/document/closing_documents/download/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/general/document/closing_documents/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/general/financial/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/hotel/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/info/dump/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/hotel/info/incremental_dump/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/hotel/matching/dump/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/booking/finish/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/booking/finish/status/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/booking/form/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/cancel/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/document/info_invoice/download/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/document/single_act/download/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/document/voucher/download/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/order/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/hotel/reviews/dump/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/hotel/static/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/search/serp/hotels/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/search/hp/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/search/multicomplete/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/order/add/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/create/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/disband/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/document/invoice/download/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/info/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/pay/overpay/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/ordergroup/order/remove/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/overview/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 100,
            "seconds_number": 86400,
        },
        {
            "endpoint": "api/b2b/v3/profiles/create/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/profiles/delete/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/profiles/disable/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/profiles/edit/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/profiles/list/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/profiles/restore/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/b2b/v3/search/serp/region/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
        {
            "endpoint": "api/affiliate/v3/overview/",
            "is_active": True,
            "is_debug_mode": False,
            "is_limited": True,
            "requests_number": 30,
            "seconds_number": 60,
        },
    ],
}
